### ISSUE TITLE
Propose a new feature: the agent management portal provide a button to fetch the agent application.yml config

### ISSUE THREAD

**Issue by hydraxman** [microsoft/HydraLab#195]
Propose a new feature: the agent management portal provide a button to fetch the agent application.yml config, so the user don't have to edit it by themselves.
![Agent_config_design](https://user-images.githubusercontent.com/8344245/209550586-582d950d-67f6-4ef9-9e18-61339287ed55.png)

**Comment by MarianConstantinMarica** [comment]
Can I work on this feature?

**Comment by hydraxman** [comment]
> Can I work on this feature?

Sure thing, are you clear about the detail work and expectation for it? I'm not sure whether this description is clear enough.

**Comment by MarianConstantinMarica** [comment]
If I understand well you want a button for fetching the agent config (name, id and secret) in application.yml.

**Comment by MarianConstantinMarica** [comment]
I want to know if you want also to automate the copy operation (cp agent/application-sample.yml application.yml) when click the button!

**Comment by MarianConstantinMarica** [comment]
Or If you want to generate the application.yml file directly in root folder with fetched data when the button is clicked, the copy operation will no longer be needed!

**Comment by MarianConstantinMarica** [comment]
What text do you want to put on the button?

**Comment by hydraxman** [comment]
Thanks so much, your understanding is quite right! When clicking the button, user will get a triggered download action, and get a downloaded application.yml file containing the agent configurations. @zhou9584 and @lifesaver0129 can help you review the PR.

As for the button text, I assume it should be a material design icon with the same style as the 2 on the right and the alt text can be "Download agent config file: application.yml".

**Comment by hydraxman** [comment]
@MarianConstantinMarica I've assigned this issue to you. @zhou9584 please help answer Marian's question during the development, thanks.

**Comment by MarianConstantinMarica** [comment]
I made the PR!

**Comment by zhou9584** [comment]
> 

PR has been merged. Thank you for your contribution.
