### ISSUE TITLE
Center/Agent/Uber dev env GitHub docker image publishing

### ISSUE THREAD

**Issue by hydraxman** [microsoft/HydraLab#196]
Please refer to the following link to learn about the details
- https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry
- https://github.com/microsoft/HydraLab/packages

**Comment by hydraxman** [comment]
Assign this to @olivershen-wow

**Comment by hydraxman** [comment]
The expected outcome of this item is to:
- To further minimize the dev debugging / first try-out experience with Docker image.

The docker should contain and keep the 2 services: center and agent running at the same time and expose the center port for API servicing. So basically this new docker image is a combination of the https://github.com/microsoft/HydraLab/blob/main/center/Dockerfile and https://github.com/microsoft/HydraLab/blob/main/agent/Dockerfile.

**Comment by hydraxman** [comment]
This uber all-in-one image help provide a smooth out-of-box with this Docker image. And a known issue is how we provide the agent identity info to the center and make the registration work. Maybe we can preset an data entry in the center sqlite db for the agent info and pass it to the agent config thru env or other channels.

**Comment by olivershen-wow** [comment]
Completed, see readme for usage guide of out-of-box uber image.
