### ISSUE TITLE
Design a holistic performance testing solution and implement it in Hydra Lab

### ISSUE THREAD

**Issue by hydraxman** [microsoft/HydraLab#199]

**Comment by hydraxman** [comment]
@taoran6, @zhou9584, @dinghong2233 and I are working on this. @taoran6 please take over this, I will assign this to you.

**Comment by hydraxman** [comment]
The draft version is available in #193

**Comment by taoran6** [comment]
The implementation of the Hydra Lab performance testing solution is completed.

Related pull request:
![image](https://user-images.githubusercontent.com/30514480/230558634-3af1a7ab-4ff5-4eb0-beb4-8f0eb60409db.png)
![image](https://user-images.githubusercontent.com/30514480/230558805-056ac4b2-caf1-4725-a93a-82940299260e.png)

Close this issue cc @hydraxman @zhou9584 @dinghong2233
