### ISSUE TITLE
Jar name confusion

### ISSUE THREAD

**Issue by hydraxman** [microsoft/HydraLab#202]
In [Agent Install.zip](https://github.com/microsoft/Hydra-Lab/files/9306692/Agent.Install.zip), after unzip, the xml points to a jar with name of "network_agent.jar", but the build output name is "agent.jar". Please help clean up the [Agent Install.zip](https://github.com/microsoft/Hydra-Lab/files/9306692/Agent.Install.zip) to make it reflect the latest state.

![image](https://user-images.githubusercontent.com/8344245/209646333-a23d9bfa-93b7-41a5-be13-f826f0eed278.png)

**Comment by hydraxman** [comment]
![image](https://user-images.githubusercontent.com/8344245/209648029-dba4becf-30fe-4e9e-ad7a-4ea7e9484d58.png)
Could this be a relative path? @zhou9584

**Comment by hydraxman** [comment]
This zip install package should be a build output, we may wrap it with a gradle task and upload it as part of a release archive. And in the wiki, the download link points to the latest version. @zhou9584

**Comment by zhou9584** [comment]
Have update the wiki and will close the issue. @hydraxman

**Comment by zhou9584** [comment]
PR is #227
