### ISSUE TITLE
Replace log file path when run install script

### ISSUE THREAD

**Issue by zhou9584** [microsoft/HydraLab#248]
I'm not sure if actionable, but could we further automate these 2 steps?
<img width="936" alt="image" src="https://user-images.githubusercontent.com/121116183/212783283-4ab1586e-b714-4268-892f-85bc96cf5c45.png">

Like we could create a new install.bat/install.ps with the following pseudo-code:

```bash
$currentPath=Get-Current-Absolute-Path
Replace-Text-In-File AgentService.xml '{LOG_FILE_LOCATION}' "$currentPath\service-log"
.\AgentService.exe install
```

So that all the user need to do is to run the install.bat with admin permission.

Feel free to do this in another PR.

_Originally posted by @hydraxman in https://github.com/microsoft/HydraLab/pull/227#discussion_r1071642675_

**Comment by DexterDreeeam** [comment]
One Line Installer is avalable to replace log path
