### ISSUE TITLE
Readability of page 'Deploy-a-test-agent-service'

### ISSUE THREAD

**Issue by DexterDreeeam** [microsoft/HydraLab#286]
Hey, I just follow steps in this page [Deploy-a-test-agent-service](https://github.com/microsoft/HydraLab/wiki/Deploy-a-test-agent-service)

I found it doesn't make much sense.
I need to do E2E test.
I expect the guide should be:

`
Choose Test Type:
    1. Xxxx
    2. E2E test
    3. Xxxx
`

Once I select Second Choice. The following steps are all about E2E test.
But I have to say flow is not easy to read.
I follow a lot steps of Android-only Agent setup steps, and it doesn't work.
Next line in guide told me, 'Yeah, these steps doesn't work for E2E, these are E2E test steps.'

I think this is very normal for a person who is not very familiar with this project.
Could we org these wiki more readable for **specific occasion**.

**Comment by hydraxman** [comment]
@DexterDreeeam could you help improve the wiki?

**Comment by DexterDreeeam** [comment]
> @DexterDreeeam could you help improve the wiki?

Sure, I will try

**Comment by hydraxman** [comment]
Assigned this issue to you @DexterDreeeam, let me know if you are facing challenges.

**Comment by hydraxman** [comment]
Onboarding 业良： [Oh My Zsh - a delightful & open source framework for Zsh](https://ohmyz.sh/) 可惜Windows上没法直接用 

大致是： 一行命令搞定>docker类容器>命令脚本>安装程序GUI>虚拟环境下载>短文档>长文档>教程>口口相传

**Comment by hydraxman** [comment]
This one is linked to #241 which is about center onboarding and user try-out.

**Comment by DexterDreeeam** [comment]
I prefer One-Line-Command, I'll try this week

**Comment by DexterDreeeam** [comment]
done
