### ISSUE TITLE
Is it possible to simplify the dependencies to provide a less painful onboarding experience

### ISSUE THREAD

**Issue by AC-Phoenix** [microsoft/HydraLab#293]
The current onboarding process is a little bit complicated which may dissuade some people who want to try it. Would like to see a more streamlined onboarding experience.

**Comment by hydraxman** [comment]
Thank you @AC-Phoenix, could you elaborate a bit on the pain? Are you trying to set up a test agent or you are trying to trigger a test task?

**Comment by hydraxman** [comment]
Confirmed with @dinghong2233 that this may be duplicated with #286, if so we can close this as dup. @AC-Phoenix

**Comment by AC-Phoenix** [comment]
Closed due to duplication.

**Comment by hydraxman** [comment]
@AC-Phoenix Thank you for reporting this and handling it as well. Just want to say we do value this feedback and will prioritize and take action to improve. And from my view the critical part now is about:
- What are the exact detail problems of the issue and how should we break it down?
- What is the right solution/path to incrementally tune this up?
Something we can do is to try it out by ourselves and hear our customers' voices. So if you have any specific issues in this area, please do keep reporting and we will appreciate the effort.
