### ISSUE TITLE
whoever made this needs to be fired

### ISSUE THREAD

**Issue by HyperSkys** [microsoft/HydraLab#491]
this code sucks, it's design is horrible. whoever made this or even contributed needs to step up there game because they just don't know how to code

**Comment by hydraxman** [comment]
Thank you for the suggestion, we will improve the design.

**Comment by hydraxman** [comment]
Actually, we are improving the code, on UT, and try to apply TDD. And if you can be more specific, we are all ears. What you said is a bit hurt, but we are still passionate about making progress to drive the changes in the test automation area.
