### ISSUE TITLE
Monkey Test中Task configuration页的含义是什么？/ The meaning of Task configuration Page in Monkey Test

### ISSUE THREAD

**Issue by Yuyuyang** [microsoft/HydraLab#551]
很喜欢这个应用，但是Task configuration Page页中Test config、Needed Permission和Device Actions的三个参数设置不是很明白。
I like Hydra Lab. However, I don't understand how to set Test config, Needed Permission and Device Actions in Task configuration Page.

<img width="1366" alt="image" src="https://github.com/microsoft/HydraLab/assets/25746471/a5de462a-7e2c-438e-884f-af64940571b8">

举例来说，我想在一次Monkey Test中进行250000次事件，并且我希望在一个小时内完成。我发现如果仅在Max step count和Test time out  second中进行设置，Test会在三分钟左右完成。我该如何设置才能实现我的目的？我知道Android ADB中的Monkey可以设置一系列的参数来进行控制，我该在哪里设置类似 --throttle 的参数？
For example, I would like to perform 250,000 steps in a single Monkey test, and I would like to finished it in about one hour. I figured that if I only set Max step count and Test time out  second as the picture above, the test will be finished in 3 minutes. How should I set to satisfy it? I know in Android ADB's Monkey, I can set parameter like -- throttle to do it. What should I do in Hydra Lab?

非常你们的帮助！
Thank you very much!

**Comment by hydraxman** [comment]
首先，感谢你的支持和贴心的双语沟通，我们团队中国同学为主所以用中文沟通完全没问题。针对你的疑问，我会请 @olivershen-wow 帮忙解答，有可能是个开发需求。稍等回复

**Comment by zhou9584** [comment]
Test config 输入配置 {"config":"--throttle 100 -v -v"}，后端会把Test config对象的value拼接到命令行中
![image](https://github.com/microsoft/HydraLab/assets/26757995/bf339b7a-0fbb-4398-9a48-6a526e03e763)

**Comment by zhou9584** [comment]
Needed Permission：是测试之前需要额外授予的应用权限
Device Actions 可以参考这个wiki https://github.com/microsoft/HydraLab/wiki/Test-Task-Customization#test-lifecycle-action-customization

**Comment by Yuyuyang** [comment]
非常感谢二位的回复，@zhou9584 的回复解决了我的困惑，再次感谢！
