### ISSUE TITLE
What are the main problems solved by HydraLab and how it is used? Do you have any specific documents?

### ISSUE THREAD

**Issue by chongxiaochao** [microsoft/HydraLab#585]

**Comment by hydraxman** [comment]
Here is a blog about it: https://medium.com/microsoft-mobile-engineering/how-hydra-lab-empowers-microsoft-mobile-testing-e4bd831ecf41

And here is the project wiki: it includes the introduction, integration guideline and manual.

@chongxiaochao thank you for the interest, will close this issue if you have no further asks.

**Comment by hydraxman** [comment]
We thought we have clarified what Hydra lab is in the README.md, however it seems you still have questions, please let us know how we can improve the clarity of the README, thanks.
