### ISSUE TITLE
用docker部署的时候报错AGENT_ID解析不了

### ISSUE THREAD

**Issue by this-scientist** [microsoft/HydraLab#635]
![clipbord_1704262775688](https://github.com/microsoft/HydraLab/assets/39897536/9490a659-c36f-4764-b44e-9bd3933b007c)
能帮忙看下是缺了什么配置还是代码的问题吗

**Comment by olivershen-wow** [comment]
Hi @this-scientist，想确认下，你在跑的是agent docker还是uber docker？

如果是agent docker，你需要手动在已启动的center portal中注册agent，然后修改agent的yml文件，指定AGENT_ID等必须的参数。可以参考[Deploy Agent Docker Container](https://github.com/microsoft/HydraLab/wiki/Deploy-Agent-Docker-Container)

如果是uber docker，应该是因为你本地有缓存的问题。
**docker run -p 9886:9886 --name=hydra-lab ghcr.io/microsoft/hydra-lab-uber:latest** 命令会优先从你本地找对应tag的docker image，你需要优先执行**docker pull ghcr.io/microsoft/hydra-lab-uber:latest**，再执行docker run。

**Comment by this-scientist** [comment]
![1704852548578](https://github.com/microsoft/HydraLab/assets/39897536/d5f33f5d-1f7f-4372-a86f-3d976a9bf071)
![1704852575454](https://github.com/microsoft/HydraLab/assets/39897536/1e3c0ddf-846b-4dd3-971f-a9a2d02a550e)
![1704852604545](https://github.com/microsoft/HydraLab/assets/39897536/30590892-a709-4383-aa1b-50dd6df71252)
我跑的是uber docker，重新拉了一次再部署，还是报这个错。我用的是腾讯云服务器跑的，不知道有没有影响。

**Comment by olivershen-wow** [comment]
有可能是腾讯云服务器的问题，你可以尝试下以下两种方案：
- 尝试在腾讯云上修改docker命令中的`latest`为指定版本`169334`，再run下试试
- 尝试本地起docker跑一下，看会不会碰到同样的问题。

按理说上传的Uber image中已经携带了默认AGENT_ID，不应该出现和这个变量相关的问题。
如果以上两种方案还是不行，试一下手动指定AGENT_ID`docker run --env AGENT_ID=default_agent_id --name=hydra-lab ghcr.io/microsoft/hydra-lab-uber:latest`

**Comment by this-scientist** [comment]
好的，指定版本为169334已经可以部署了，感谢！
